### ISSUE TITLE
Fans spike to 100% on suspend

### ISSUE THREAD

**Issue by notadoktor** [tuxedocomputers/tuxedo-control-center#270] opened 2023-02-20 10:28 UTC
I have a Stellaris Gen4 with Ryzen9 / 3070 Ti. It is finally able to suspend / wake without issue, but now all the fans spike to 100% when the laptop is suspended. They stay at 100% until it is woken up again.

OS: Ubuntu 22.04.01 LTS on X11
TCC: v1.2.4
nvidia: 525.78.01

**Comment by manfredlotz** [comment] 2024-03-01 11:44
I have a similar problem using
- TUXEDO Polaris 17
- EndeavouOS
  - tuxedo-drivers-dkms is installed
  - now tuxedo-control-center-bin is deinstalled
  

It started in early January that when waking up from suspend the fans went to 100% for > 5sec and < 10 sec. Uninstalling tuxedo-control-center-bin helped here.

If there is anything I can debug please tell and I will do.

**Comment by manfredlotz** [comment] 2024-04-09 16:36
Having installed tuxedo-control-center-bin 2.1.8-2 and it seems that the fan is back to normal when waking up from suspend.

**Comment by tuxedoder** [comment] 2024-04-09 17:52
> but now all the fans spike to 100% when the laptop is suspended. They stay at 100% until it is woken up again.

Tested on Stellaris 15 Gen 4 i7-12700H and I can't reproduce errors with 2.1.8. Fan problems should be fixed in 2.1.8. I think this issue can most likely be closed.

> Having installed tuxedo-control-center-bin 2.1.8-2 and it seems that the fan is back to normal when waking up from suspend.

That is not related to the original issue since the mentioned time frames suggest something else and in 2.1.8 fan behavior got adjusted which was mentioned in https://github.com/tuxedocomputers/tuxedo-control-center/issues/364.

**Comment by manfredlotz** [comment] 2024-04-09 18:38
Whatever the reason is the problem I had has gone. :-)

**Comment by tuxedoder** [comment] 2024-05-08 21:51
Since there has been no response and I can't replicate this problem on the newest version, I will close this issue.

**Closed by tuxedoder** 2024-05-08 21:51 UTC
