### ISSUE TITLE
tccd mit 100% CPU since update to 2.1.1

### ISSUE THREAD

**Issue by robby81** [tuxedocomputers/tuxedo-control-center#336] opened 2023-12-19 08:19 UTC
Since I updated tuxedo-control-center here on openSUSE Tumbleweed, I get crazy fan and 100% CPU for the tccd process.
Moreover, when I open the desktop it, it says, cannot connect to demon.
Thus way it is barely usable and without tccd the fan will not switch off at all.

**Comment by munix9** [comment] 2023-12-19 08:37
is there perhaps something useful in the logs?

eg. with `sudo journalctl -b -u tccd`

**Comment by robby81** [comment] 2023-12-19 09:15
~> sudo journalctl -b -u tccd
[sudo] password for root: 
Dez 19 08:37:38 localhost systemd[1]: Started TUXEDO Control Center Service.
Dez 19 08:37:39 localhost tccd[1555]: Starting daemon v2.1.1 (node: v14.20.0 arch: x64)
Dez 19 08:37:39 localhost tccd[1555]: tuxedo-io ver 0.3.9 [ interface: uniwill ]
Dez 19 08:37:39 localhost tccd[1555]: Filled missing settings with default: /etc/tcc/settings
Dez 19 08:37:40 localhost.localdomain tccd[1555]: Detected white only keyboard backlight
Dez 19 08:37:40 localhost.localdomain tccd[1555]: ODMPowerLimitWorker: Set ODM TDPs ["45 W","60 W","110 W"]
Dez 19 08:37:40 localhost.localdomain tccd[1555]: Daemon started
Dez 19 08:37:47 localhost.localdomain tccd[1555]: Authorization required, but no authorization protocol specified
Dez 19 08:37:47 localhost.localdomain tccd[1555]: Authorization required, but no authorization protocol specified
Dez 19 08:37:47 localhost.localdomain tccd[1555]: Authorization required, but no authorization protocol specified
Dez 19 08:37:47 localhost.localdomain tccd[1555]: Authorization required, but no authorization protocol specified
Dez 19 08:37:47 localhost.localdomain tccd[1555]: Authorization required, but no authorization protocol specified

**Comment by robby81** [comment] 2023-12-19 09:16
BTW, keyboard backlight does not work here as well, but this never worked

System:
Operating System: openSUSE Tumbleweed 20231217
KDE Plasma Version: 5.90.90
KDE Frameworks Version: 5.247.0
Qt Version: 6.6.1
Kernel Version: 6.6.6-1-default (64-bit)
Graphics Platform: Wayland
Processors: 20 × 13th Gen Intel® Core™ i7-13700H
Memory: 62.5 GiB of RAM
Graphics Processor: Mesa Intel® Graphics
Manufacturer: TUXEDO
Product Name: TUXEDO InfinityBook Pro Gen8 (MK1)

**Comment by munix9** [comment] 2023-12-19 09:20
hm, you can try the following as the logged-in user in a shell:

`xhost +si:localuser:root`

**Comment by robby81** [comment] 2023-12-19 09:54
what is the idea behind this?

**Comment by munix9** [comment] 2023-12-19 10:06
the root user running the tccd service is trying to access the user's graphical output and is not allowed to do so - something like that.

**Comment by munix9** [comment] 2023-12-19 10:11
if this is the case, then something has been changed that is causing the problem. tuxedo needs to take a closer look and find a solution.

with `xhost` you grant other users/hosts access to the graphical output (X/Wayland).

not very nice, because it can be problematic in terms of access permissions and security, but now ...

**Comment by robby81** [comment] 2023-12-19 11:45
ystemctl stop tccd.service
localhost:/home/robby # /opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/service/tccd --start
Starting daemon v2.1.1 (node: v14.20.0 arch: x64)
tuxedo-io ver 0.3.9 [ interface: uniwill ]
Filled missing settings with default: /etc/tcc/settings


--> after starting this way, the tccd is at 100% again

**Comment by munix9** [comment] 2023-12-19 11:48
then unfortunately I can't help any further, let's see what tuxedo has to say.

**Comment by robby81** [comment] 2023-12-19 14:30
Is there a possibility to calm down the fan and make the keyboard backlight working without the tuxedo-specific packages? With my older 4 years old Infinity Book it worked out of the box without installation of tuxedo packages??

**Comment by thrasymache** [comment] 2023-12-19 15:14
I have the impression that tccd is supposed to optimize battery life, but my Aura15 Gen 2 had a single CPU at 100% for tccd, and when I stopped the daemon the predicted life of the battery jumped from one hour to more than two, so it's a huge battery drain right now.

(I previously posted this in https://github.com/tuxedocomputers/tuxedo-control-center/issues/37)

**Comment by robby81** [comment] 2023-12-19 15:18
If I login to the X11 session or the IceWM session, the tccd does not go crazy. It appears to only affect the wayland session. I am wondering, that the daemon has to do with the graphical system?

**Comment by thrasymache** [comment] 2023-12-19 16:22
I should have mentioned that I use i3 as my window manager, which seems to have caused related issues before, for instance with keyboard shortcuts for the keyboard backlight.

> I have the impression that tccd is supposed to optimize battery life, but my Aura15 Gen 2 had a single CPU at 100% for tccd, and when I stopped the daemon the predicted life of the battery jumped from one hour to more than two, so it's a huge battery drain right now.
> 
> (I previously posted this in #37)

**Comment by kron4eg** [comment] 2023-12-19 17:26
Yesterday I also ran into this issue under Fedora 39, on Infinity Book 16.

After upgrading tcc to the latest 2.1.1 the UI started to fail (i.e. never shown). So I've found it wasn't able to speak to tccd which was spinning 1 cpu core to 100%.

**Comment by kron4eg** [comment] 2023-12-19 21:04
> If I login to the X11 session or the IceWM session, the tccd does not go crazy. It appears to only affect the wayland session. I am wondering, that the daemon has to do with the graphical system?

Indeed. On Fedora 39 if I switch to Gnome Xorg, tccd behaves good and everything is working.

**Comment by robby81** [comment] 2023-12-19 22:47
@munix9 : would it be an option for you to revert back to the previous version that worked in your tumbleweed repo? Or can I download a rpm of it anywhere?

**Comment by munix9** [comment] 2023-12-19 22:57
> @munix9 : would it be an option for you to revert back to the previous version that worked in your tumbleweed repo? Or can I download a rpm of it anywhere?

see https://build.opensuse.org/package/show/home:munix9:test/tuxedo-control-center
https://software.opensuse.org//download.html?project=home%3Amunix9%3Atest&package=tuxedo-control-center

**Comment by Bundy01** [comment] 2023-12-20 01:08
@robby81 
> If I login to the X11 session or the IceWM session, the tccd does not go crazy. It appears to only affect the wayland session.

unfortunately, it's not Wayland's fault. I use DE Cinnamon with Xorg. [335](https://github.com/tuxedocomputers/tuxedo-control-center/issues/335#issuecomment-1863680630)

**Comment by mfortini** [comment] 2023-12-20 11:08
Same here on Debian testing. 100%CPU and fans spinning like crazy. Tuxedo Control Center exits

**Comment by biberino** [comment] 2023-12-20 14:48
Same on fedora 39.

The Problem is https://github.com/tuxedocomputers/tuxedo-control-center/blob/95f5ae541fd8ceb01a9820e4df3f32e2c82a54d6/src/common/classes/XDisplayRefreshRateController.ts#L38

This Regex match lasts forever at 100% CPU. Not sure what changed and why this regex suddenly behaves like this.

**Comment by mattbrun** [comment] 2023-12-20 16:39
I confirm the issues on Archlinux as well with tccd v2.1.1.
It was working like a charm before.

**Comment by mattbrun** [comment] 2023-12-20 16:39
I confirm the issues on Archlinux as well with tccd v2.1.1.
It was working like a charm before.

**Comment by kron4eg** [comment] 2023-12-20 16:46
> Not sure what changed and why this regex suddenly behaves like this

I suppose it's not the regexp itself, but rather `setEnvVariables()` being called in cycle. @biberino how do you know it's that code being "hot" BTW?

**Comment by tuxedoxt** [comment] 2023-12-20 17:00
Hello,

i've confirmed that it's actually the regex call and merged the suggested fix from @BlackJohnny 

https://github.com/tuxedocomputers/tuxedo-control-center/pull/338

As long as there's not a second culprit, that should do it :crossed_fingers:

**Comment by biberino** [comment] 2023-12-20 17:07
The new Regex works :+1:

**Comment by ARIASFREDERIC** [comment] 2023-12-21 10:18
I have same issue on my laptop .... 100% of CPU and 100% of fan. And it's tccd who take all CPU (top command)

**Comment by thrasymache** [comment] 2023-12-23 06:26
My machine is currently hanging in the upgrade to 2.1.2: 
```
tuxedo_nb05_sensors.ko.zst:
Running module version sanity check.
 - Original module
   - No original module exists within this kernel
 - Installation
   - Installing to /lib/modules/6.5.0-10010-tuxedo/updates/dkms/

depmod...
Check tccd running status
inactive
(Re)load modules if possible

Progress: [ 60%] [#################################################################################.......................................................]

```

**Comment by thrasymache** [comment] 2023-12-26 03:22
I had previously stopped the tccd daemon since it couldn't be optimizing either battery life or performance when it was the primary consumer of CPU cycles on the system. I had to SIGTERM the `apt` process to get it to stop after waiting for days to see if it would progress. Then when my system wouldn't suspend anymore I restarted. I had to resort to Magic SysRq keys to reboot the system since even the SIGKILL that `systemd` was sending to `modprobe` wouldn't stop it. After a restart there are no reported updates to install and `tccd` is back to consuming 3% of CPU which still sometimes makes it the primary consumer of CPU cycles on the system.

ProTip: it is best not to drop poorly tested updates immediately before a holiday weekend.

**Comment by mfortini** [comment] 2023-12-27 08:31
Had to `sudo kill -9 ` tuxedo control center to finish the upgrade

> My machine is currently hanging in the upgrade to 2.1.2:
> 
> ```
> tuxedo_nb05_sensors.ko.zst:
> Running module version sanity check.
>  - Original module
>    - No original module exists within this kernel
>  - Installation
>    - Installing to /lib/modules/6.5.0-10010-tuxedo/updates/dkms/
> 
> depmod...
> Check tccd running status
> inactive
> (Re)load modules if possible
> 
> Progress: [ 60%] [#################################################################################.......................................................]
> ```

**Comment by tuxedoherbert** [comment] 2024-02-16 12:26
Should get fixed already

**Closed by tuxedoherbert** 2024-02-16 12:26 UTC
