### ISSUE TITLE
Keyboard backlight no longer start after boot on Polaris 17 after TCC update

### ISSUE THREAD

**Issue by Uhter** [tuxedocomputers/tuxedo-control-center#288] opened 2023-04-04 09:12 UTC
Hello everyone,

After update Tuxedo Control Center to v2.0.2-1, Keyboard Backlight is off at boot (also [Fn] + [space] backlight shortcut doesn't work anymore and I opened an [other issue](https://github.com/tuxedocomputers/tuxedo-keyboard/issues/169)) and after boot I have to open _TCC > Keyboard Backlight_ and move the cursor a few times to turn backlight on!

Configuration:

-  TUXEDO Polaris 17 AMD Gen3
-  BIOS: N.1.50A12
- EC: 1.32.29
- Manjaro Xfce
- kernel 6.2.8-1 and headers 6.2.8-1
- TTC 2.0.2-1
- Tuxedo keyboard dkms 3.2.1-1
- lsmod | grep -E "clevo|tuxedo" :
```clevo_wmi              20480  0
wmi                    45056  7 video,uniwill_wmi,clevo_wmi,asus_wmi,wmi_bmof,mxm_wmi,nouveau
tuxedo_io              24576  0
tuxedo_keyboard        77824  3 tuxedo_io,uniwill_wmi,clevo_wmi
sparse_keymap          16384  2 asus_wmi,tuxedo_keyboard
led_class_multicolor    16384  1 tuxedo_keyboard
```

What's wrong?

**Comment by TiGR** [comment] 2023-04-07 10:11
I had the same issue here on Aura 15 Gen 1. Rebooting system helped. It seems to be happening on every TCC update now.

**Comment by Uhter** [comment] 2023-04-07 13:01
Hi @TiGR,

I rebooted few times ans tried 3 different kernels, the issue is still there.
Thanks for your advice :)

**Comment by Matombo** [comment] 2023-04-17 15:12
Since tuxedo-keyboard 3.2.0 the driver no longer handles fn+space itself but sends a KEY_KBDILLUMTOGGLE event to the userspace where the Desktop environment handles it. GNOME and KDE by default then toggle they keyboard backlight via the /sys/class/leds interface, but XFCE has this shortcut not bound by default as it seems (as far as i quickly checked, XFCE has no keyboard backlight controll at all?).

**Comment by Nintendo7686** [comment] 2023-04-28 09:04
On Pulse 14, Manjaro KDE, the keyboard backlight does not start automatically since 3.2.0. The laptop will turn on and the backlight will be OFF (even with the last state left at ON). Using Fn+Space returns backlight set to 0% (OFF), which means nothing happens since the backlight was already OFF. I can then Fn+Space again to turn it ON to whatever setting in my TCC settings. The backlight works fine with sleeping.

**Comment by Matombo** [comment] 2023-05-16 13:11
> On Pulse 14, Manjaro KDE, the keyboard backlight does not start automatically since 3.2.0. The laptop will turn on and the backlight will be OFF (even with the last state left at ON). Using Fn+Space returns backlight set to 0% (OFF), which means nothing happens since the backlight was already OFF. I can then Fn+Space again to turn it ON to whatever setting in my TCC settings. The backlight works fine with sleeping.

This is a different device and a different issue, please open a new bug if the issue persists with the current version.

**Comment by Uhter** [comment] 2023-05-16 14:07
Keyboard backlight works again and [Fn] + [space] too, since I updated kernel from v6.2.13 to v6.3.0 and upgraded Tuxedo Control Center to 2.0.5 (but I can't change keyboard color because "Your device has no keyboard backlight or is not (yet) supported by this control interface.").

I don't know for the moment who solved the issue: new linux kernel or TTC which does not support keyboard?

**Comment by Matombo** [comment] 2023-05-16 15:59
Pulse 14 should be supported. Which version of tuxedo-keyboard are you running?

Can you post the output of `dkms status`?

**Comment by Matombo** [comment] 2023-05-16 16:02
PS.: Pulse has a white only keyboard, so you should see just a brightness slider there

**Comment by TiGR** [comment] 2023-05-17 05:02
Aura 15 Gen 1. No, the reboot did not help actually, as I reported earlier. I have this issue too. Sometimes it boots with no controls working (and I cant turn it off or turn it on if needed). Sometimes it breaks after sleep. Sometimes it works. But most of the time it is completely unreliable.

Also, the backlight tab in TCC sometimes contains only one slider, and sliding it produces no effect. Sometimes it is all working - there is a color picker and slider and it all works. Sometimes it just says that the device is not supported.

**Comment by Nintendo7686** [comment] 2023-05-17 09:49
> Pulse 14 should be supported. Which version of tuxedo-keyboard are you running?
> 
> Can you post the output of `dkms status`?

`dkms status` output below.

```
Error! Could not locate dkms.conf file.
File: /var/lib/dkms/tuxedo-keyboard/3.0.8/source/dkms.conf does not exist.
```
TCC version is 2.0.4, kernel 6.3.0

**Comment by Matombo** [comment] 2023-05-17 12:43
> > Pulse 14 should be supported. Which version of tuxedo-keyboard are you running?
> > Can you post the output of `dkms status`?
> 
> `dkms status` output below.
> 
> ```
> Error! Could not locate dkms.conf file.
> File: /var/lib/dkms/tuxedo-keyboard/3.0.8/source/dkms.conf does not exist.
> ```
> 
> TCC 2.0.4, tuxedo-keyboard-dkms 3.2.3 (Manjaro Official repositories - community), and kernel 6.3.0

That's the whole dkms output?
Normaly it should have this format

```
$ dkms status
tuxedo-keyboard/3.2.3, 6.2.0-10005-tuxedo, x86_64: installed
tuxedo-keyboard/3.2.3, 6.2.0-10007-tuxedo, x86_64: installed
```
(i'm currently on a ubuntu install, so ignore the slightly different version format)

Seems like something broke on the package level on your system and tuxedo-keyboard did not get build at all. tuxedo-keyboard 3.2.3 should just build fine for linux 6.3.

Double check if you habe linux63-headers installed please.
You can try to completly remove tuxedo-keyboard and install it again.
If that doesn't help the Manjaro forum might give you better hints what broke the package then I can.

When you fixed the dkms issue and the backlight issue persists please report back here with another `dkms status`.

**Comment by Matombo** [comment] 2023-05-17 12:49
Closing this issue now because now here are 3 different devices discussed and this will lead to confusion

@Nintendo7686 If the issue persists after you have fixed the dkms error please open a new issue for the Pulse 14 Gen1

@TiGR Please open a seperate issue for the Aura 15 Gen1 and describe your exact issue independently from the comments here.

**Comment by Nintendo7686** [comment] 2023-05-17 12:50
> That's the whole dkms output?

Yup, that is the whole thing.

> Seems like something broke on the package level on your system and tuxedo-keyboard did not get build at all. tuxedo-keyboard 3.2.3 should just build fine for linux 6.3.

Previously I was on linux 6.2 and this was not working. Today I moved to linux 6.3 but the issue still stands.

> Double check if you habe linux63-headers installed please.

I can confirm headers are installed.

> You can try to completly remove tuxedo-keyboard and install it again.

I have done that, it did not help.

I will move this issue to Manjaro Forum and stop posting on this ticket. Thanks for the support.

**Closed** 2023-05-17 12:53 UTC

**Comment by Uhter** [comment] 2023-05-17 13:38
@Nintendo7686 
Can you give a link to your post on Manjaro Forum please?

**Comment by Nintendo7686** [comment] 2023-05-17 14:39
@Uhter of course, please look [here](https://forum.manjaro.org/t/keyboard-backlight-no-longer-starts-after-boot-on-tuxedo-pulse-14/140691?u=danoselti)
