### ISSUE TITLE
TCC prevents dGPU from going to D3cold state

### ISSUE THREAD

**Issue by salihmarangoz** [tuxedocomputers/tuxedo-control-center#360] opened 2024-02-15 15:10 UTC
PCI-Express Runtime D3 (RTD3) Power Management is a very important feature for achieving longer battery times [(driver readme)](https://us.download.nvidia.com/XFree86/Linux-x86_64/535.154.05/README/dynamicpowermanagement.html). While D0 being the highest power state, it may be switched to other states for power-saving. With RTD3, it is possible to power-off dGPU with D3cold state. Print the state via this command:

```bash
$ cat /sys/bus/pci/devices/0000:01:00.0/power_state
```

The problem is, TCC keeps the dGPU awake all the time. Exiting the TCC is not enough. I had run `sudo service tccd stop` to let the dGPU switch to D3cold state. After I started the `tccd` service again, it was still in D3cold, but after opening the TCC again it switched to D0 state. 

This is frustrating because I lower CPU freq using TCC for battery saving, but it wastes energy by keeping the dGPU awake. 

Maybe related to #341

**Comment by tuxedoxt** [comment] 2024-02-15 15:17
Hello,

leaving the TCC dashboard should be enough to stop polling dGPU for info and let it go to d3cold. Going to the dashboard alone should also not wake the dGPU if at the time it's in d3cold.

Does this fit? Any other behaviour I would characterize as a bug.

**Comment by silles79** [comment] 2024-02-15 15:41
For me opening the dashboard does change d3cold to d0 and keeps it there until
closing it and will go back to d3cold.

**Comment by salihmarangoz** [comment] 2024-02-15 15:50
I checked with `forkstat` for catching newly created processes. I see this process is running routinely: `/bin/sh -c nvidia-smi --query-gpu=power.draw,power.max_limit,enforced.power.limit,clocks.gr,clocks.max.gr --format=csv,noheader`

And yes, the TCC GUI is running in the background. **But it doesn't happen all the time.** I think I found a behavior that may be important to discover the bug. Maybe you can also reproduce it:

1. Open TCC.
2. Wait for CPU and iGPU values to refresh.
3. Switch to the dGPU tab.
4. Wait for a few seconds and then close the window.
5. Sometimes it keeps calling nvidia-smi on the background.

Screen record: https://www.youtube.com/watch?v=rfK6HyMgoCM

**Comment by salihmarangoz** [comment] 2024-02-19 10:17
Maybe implementing a heartbeat technique for checking that hardware information subscribers are alive would be a solution. For example, if there is no heartbeat from the GUI for 10 seconds, the daemon can assume that the GUI is killed/crashed or unable to respond. 

I checked the code but I really dont know Electron. However, after seeing many async functions this came to my mind as a solution.

**Comment by tuxedoder** [comment] 2024-02-19 18:43
The expected behavior is, that during initial startup the tcc will wake up the dGPU and thus metrics will be collected because the dGPU got woken up. The initial wakeup of the dGPU seems to happen because of electron and not because of the code itself. Once open, minimizing the window or leaving the dashboard to another part of the tcc should disable collection of metrics. Opening the minimized application will then not wake up the dGPU in the dashboard if it is in d3. Here some videos with 24.04.04 LTS via our FAI.

https://github.com/tuxedocomputers/tuxedo-control-center/assets/160256398/cca680fa-f8e4-465e-a007-e1da2597539b

It is a bit odd that it collects data once the tcc is closed and that is indeed a bug. It is a bit hard to reproduce, but I can replicate it after several attempts. I need more time to analyze and think about it. 

https://github.com/tuxedocomputers/tuxedo-control-center/assets/160256398/dac478b6-7509-421d-8b8b-6a31e0cb0c28

**Comment by silles79** [comment] 2024-02-29 14:38
Did some testing and it looks like the UI wakes up the dGPU, but only "closes" it when u switch back to iGPU tab and close it.

exiting the app while dGPU tab is open doesn't stop polling the dGPU.
Either u have to kill the tccd daemon or start the UI and switch back to iGPU and exit UI 

so I'd say this is a bug

**Comment by tuxedoder** [comment] 2024-02-29 17:44
> but only "closes" it when u switch back to iGPU tab and close it.

The dashboard does not differentiate between which tab is visible. Data is collected for all gauges while the dashboard component is visible to ensure a seamless transition between tabs.

> u have to kill the tccd daemon

That resets tccd to default values, which is off for dGPU data collection.

> It is odd that it collects data once the tcc is closed and that is indeed a bug. It is a bit hard to reproduce, but I can replicate it after several attempts. I need more time to analyze and think about it.

As a small update, debugging was not easy because I could not consistently reproduce it. Adding more verbose debug logging seemingly fixed this issue, making it harder for me to analyze the code. The dashboard component is calling the required functions and turning off the data collection. However, sometimes the dbus does not show that a value was actually set. I think tcc terminates before the signal was sent to tccd, causing it to be unable to always turn off. It appears to be a race condition.

I have considered various solutions, and a fix should arrive soon. To summarize the current idea, I plan to wait in electrons close event for a tccd value to ensure the data collection status is set correctly in normal operation. Additionally, a timeout in tccd to automatically turn off data collection if the gpu dbus functions are not called, ensuring the status is maintained if tcc crashes or closes unexpectedly.

**Comment by tuxedoder** [comment] 2024-03-25 15:13
As a small update, I tried to put various things into the next release and it got a bit delayed. Maybe this week if things go well.

**Comment by tuxedoder** [comment] 2024-04-08 18:04
Should be fixed in 2.1.8.

**Closed by tuxedoder** 2024-04-08 18:04 UTC
