### ISSUE TITLE
No "Battery charging options" on TCC 2.1.7 on Pulse 15 gen1

### ISSUE THREAD

**Issue by FedericoCeratto** [tuxedocomputers/tuxedo-control-center#366] opened 2024-03-09 13:56 UTC
As by title, the "Battery charging options" section is not showing up.

Installed packages
```
ii  tuxedo-archive-keyring         2022.04.01~tux all          GnuPG archive keys of the tuxedo archive
ii  tuxedo-control-center          2.1.7          amd64
ii  tuxedo-drivers                 4.3.1          all          Kernel modules for TUXEDO devices
ii  tuxedo-keyboard                4.3.1          all          Keyboard back-light driver for ITE devices (dummy transitional package)
ii  tuxedo-keyboard-dkms           4.3.1          all          Keyboard back-light driver for ITE devices (dummy transitional package)
```
Kernel 6.7.7-amd64

**Comment by JTheRevelator** [comment] 2024-03-10 12:14
I have the same problem. No more Battery charging options" after update.

**Comment by izacarias** [comment] 2024-03-11 17:49
Same problem here
Fedora 39
Kernel: 6.7.7-200.fc39.x86_64
Model: Infinity Book Pro (Gen 7)

rpm -qa | grep tuxedo
tuxedo-touchpad-switch-1.0.7-1.fc39.x86_64
tuxedo-drivers-4.0.2-1.fc39.noarch
tuxedo-control-center-2.1.2-1.fc39.x86_64

sudo dkms status
tuxedo-drivers/4.0.2, 6.7.7-200.fc39.x86_64, x86_64: installed

(I am using the kallepm COPR repositories. It was working till some days ago)

**Comment by crissi-tuxedo** [comment] 2024-03-18 15:36
Hello everyone,

I did a test installation and for us the battery charging options do show up.

> As by title, the "Battery charging options" section is not showing up.
> 
> Installed packages
> 
> ```
> ii  tuxedo-archive-keyring         2022.04.01~tux all          GnuPG archive keys of the tuxedo archive
> ii  tuxedo-control-center          2.1.7          amd64
> ii  tuxedo-drivers                 4.3.1          all          Kernel modules for TUXEDO devices
> ii  tuxedo-keyboard                4.3.1          all          Keyboard back-light driver for ITE devices (dummy transitional package)
> ii  tuxedo-keyboard-dkms           4.3.1          all          Keyboard back-light driver for ITE devices (dummy transitional package)
> ```
> 
> Kernel 6.7.7-amd64

What I am wondering looking at your installed packages: we recently renamed tuxedo-keyboard to tuxedo-drivers, I don't think it's nessesary to have them both installed and might be the root cause.

as for @izacarias I see a similar possible problem here, a quick google search alledged that `(original_module exists)` means dkms is throwing an error, also your whole problem looks like the classic "tuxedo-drivers not working".

I think the updating of the packages did not go smoothly and messed them up somehow.

I kindly ask you both to cleanly (purge old versions) reinstall tuxedo-drivers and see if the bug still persists.

best regards, Crissi

**Comment by izacarias** [comment] 2024-03-22 01:45
@crissi-tuxedo 

I just removed everything from Tuxedo (with `rpm -e <package_name>`) and reinstalled only the Tuxedo Drivers package.
You are right. The problem seems to be with Tuxedo Drivers because the Touchpad on/off key doesn't work (the small white dot at the top-right of the touchpad). The Aeroplane mode key doesn't work as well. 

I still need to figure out what is wrong. 
At least the DKMS command now looks right:

```
sudo dkms status 
tuxedo-drivers/4.3.2, 6.7.9-200.fc39.x86_64, x86_64: installed
```

Package versions:
```
sudo rpm -qa | grep tuxedo
tuxedo-drivers-4.3.2-1.noarch
```

best regards,
Iuli

**Comment by crissi-tuxedo** [comment] 2024-03-22 13:33
@izacarias 

as this is an issue with tuxedo-drivers, would you be so kind to open an issue over there? :)

https://github.com/tuxedocomputers/tuxedo-drivers

best regards, Crissi

**Comment by izacarias** [comment] 2024-03-26 20:10
Hi Crissi!
Just a small update:
You were totally right. My problem was related to the `tuxedo-drivers` package (therefore, it had nothing to do with the Tuxedo Control Center).

I **temporarily solved the problem by disabling the secure boot option** in my BIOS. I will open an issue on the tuxedo-drivers Gitlab repository and ask them to add this information to the README file (or try to fix the problem of key enrollment).

Thank you very much for the feedback, and sorry for "spamming" the Tuxedo Control Centre issues thread :)

Best regards,
Iuli

**Comment by crissi-tuxedo** [comment] 2024-04-02 13:04
Oh no, you are not spamming! :)

thank you for your detailed report, I will keep this in mind as a possible solution for future similar problems.

I will close this issue, as it's not a TCC issue

best regards,
Crissi

**Closed by crissi-tuxedo** 2024-04-02 13:04 UTC
