### ISSUE TITLE
Version 2.1.7 does not work on the latest Linux Mint Debian Edition

### ISSUE THREAD

**Issue by alexeymuranov** [tuxedocomputers/tuxedo-control-center#369] opened 2024-03-13 10:11 UTC
I have just tried manually installing Tuxedo software as suggested [here] under [Linux Mint Debian Edition][LMDE] 6 . Currently available versions of Tuxedo Control Center are 1.0.3, 2.0.2, 2.0.8, and 2.1.7. 

I installed 2.1.7 and tried to start it. The TCC applet appeared in the status area, but I could not launch the TCC application, and there were no sign that a new profile got applied -- the fan was spinning as usual.

Then I purged, `tuxedo-control-center` and installed the 2.0.8 version. This time I could start the TCC application normally, I saw `TUXEDO Defaults` profile applied, and the fan got quiet.

What is wrong with the 2.1.7 version?

The other Tuxedo software that I have installed manually is `tuxedo-drivers_4.3.2_all.deb` and `tuxedo-keyboard_4.3.2_all.deb`.

My kernel is `6.1.0-18-amd64`.

[here]: https://www.tuxedocomputers.com/en/TUXEDO-Control-Center-and-drivers-under-Debian.tuxedo
[LMDE]: https://linuxmint.com/download_lmde.php

**Comment by pescepalla** [comment] 2024-03-22 15:15
I can confirm that `tuxedo-control-center 2.1.7` will not run and output the following when launched from terminal:

```
(tuxedo-control-center:2707): Gtk-WARNING **: 16:12:51.404: Theme parsing error: gtk-contained-dark.css:2871:228: Missing closing bracket for :not()
(node:2707) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'on' of undefined
    at TccDBusController.onModeReapplyPendingChanged (/opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/common/classes/TccDBusController.js:568:24)
    at /opt/tuxedo-control-center/resources/app.asar/dist/tuxedo-control-center/e-app/e-app/main.js:191:13
    at Generator.next (<anonymous>)
    at fulfilled (/opt/tuxedo-control-center/resources/app.asar/node_modules/tslib/tslib.js:164:62)
(Use `tuxedo-control-center --trace-warnings ...` to show where the warning was created)
(node:2707) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
(node:2707) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

OS: Arch Linux
WM: Hyprland

**Comment by pescepalla** [comment] 2024-04-04 16:04
Solved for me with 2.1.8

**Comment by alexeymuranov** [comment] 2024-04-04 16:48
> Solved for me with 2.1.8

Not for me. Now even the applet does not show up. Tried to run from the command line:
```console
$ tuxedo-control-center
libva error: /usr/lib/x86_64-linux-gnu/dri/i965_drv_video.so init failed
```

**Comment by tuxedoder** [comment] 2024-04-08 16:45
> I installed 2.1.7 and tried to start it. The TCC applet appeared in the status area, but I could not launch the TCC application,

I tried `lmde-6-cinnamon-64bit.iso`, installed with `sudo apt install ./tuxedo-control-center_2.1.8_amd64.deb ./tuxedo-drivers_4.3.2_all.deb` and rebooted, everything seems to work as it should. `sudo systemctl status tccd` returns active and running `tuxedo-control-center` via terminal works. Try again with 2.1.8 to see if it works.

> The other Tuxedo software that I have installed manually is tuxedo-drivers_4.3.2_all.deb and tuxedo-keyboard_4.3.2_all.deb.

You only need `tuxedo-drivers`, `tuxedo-keyboard` is the old package and content moved into `tuxedo-drivers`.

> Running /opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/service/tccd reports Pkg: Error reading from file.

That arch related issue is mentioned in https://github.com/tuxedocomputers/tuxedo-control-center/issues/376 and unrelated to this issue.

**Comment by alexeymuranov** [comment] 2024-04-08 19:54
2.1.8 still does not work for me. I cannot launch the GUI app and the status icon does not appear. However, on the command line I get:
```console
$ tuxedo-control-center
TUXEDO Control Center is already running
$ sudo systemctl status tccd
[sudo] password for alexey:              
× tccd.service - TUXEDO Control Center Service
     Loaded: loaded (/etc/systemd/system/tccd.service; enabled; preset: enabled)
     Active: failed (Result: exit-code) since Mon 2024-04-08 21:48:04 CEST; 2mi>
   Duration: 440ms
    Process: 746 ExecStart=/opt/tuxedo-control-center/resources/dist/tuxedo-con>
   Main PID: 746 (code=exited, status=1/FAILURE)
        CPU: 88ms
```

**Comment by tuxedoder** [comment] 2024-04-08 20:05
`tccd` must be active for `tcc` to start. With that log alone it is not possible to see why `tccd` is not active.

**Comment by alexeymuranov** [comment] 2024-04-08 20:06
Anyway, when I install 2.0.8, it just works and no need to reboot.

**Comment by tuxedoder** [comment] 2024-04-08 20:13
Well, without more logs I really can't help. With `sudo journalctl --boot | grep tccd` you can see `tccd` related messages. You should reboot after installing to make sure though.

**Comment by alexeymuranov** [comment] 2024-04-13 10:31
@tuxedoder , here, after purging the old version (2.0.8), installing the new (2.1.8), and rebooting:
```console
$ sudo journalctl --boot | grep tccd
[sudo] password for alexey:              
Apr 13 12:29:06 Alexey-InfinityBook-LMDE systemd[1]: Started tccd.service - TUXEDO Control Center Service.
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]: pkg/prelude/bootstrap.js:1872
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:       throw error;
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:       ^
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]: Error: /tmp/pkg/90b3bf8934ee0aec9e2a02c045106849efd29b6c488ebe5ed2018dbfe90b5f0d/TuxedoIOAPI.node: failed to map segment from shared object
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at process.dlopen (pkg/prelude/bootstrap.js:2251:28)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1144:18)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Module.load (internal/modules/cjs/loader.js:950:32)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Function.Module._load (internal/modules/cjs/loader.js:790:12)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Module.require (internal/modules/cjs/loader.js:974:19)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Module.require (pkg/prelude/bootstrap.js:1851:31)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at require (internal/modules/cjs/helpers.js:101:18)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Object.<anonymous> (/snapshot/tuxedo-control-center/dist/tuxedo-control-center/service-app/native-lib/TuxedoIOAPI.js)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Module._compile (pkg/prelude/bootstrap.js:1926:22)
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10) {
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]:   code: 'ERR_DLOPEN_FAILED'
Apr 13 12:29:06 Alexey-InfinityBook-LMDE tccd[749]: }
Apr 13 12:29:06 Alexey-InfinityBook-LMDE systemd[1]: tccd.service: Main process exited, code=exited, status=1/FAILURE
Apr 13 12:29:06 Alexey-InfinityBook-LMDE systemd[1]: tccd.service: Failed with result 'exit-code'.
```

**Comment by tuxedoder** [comment] 2024-04-15 16:38
Do you have `TuxedoIOAPI.node` in `/tmp`? You can check with `sudo find /tmp -name TuxedoIOAPI.node`. It seems like one file is missing.

**Comment by alexeymuranov** [comment] 2024-04-15 22:12
@tuxedoder, I do not believe to have `nodejs` installed, should I install it? If it is a dependency of TCC, why did it not get installed?

**Comment by alexeymuranov** [comment] 2024-04-16 11:22
> Some suggest it may be a permission issue. I found 2 different solutions for that case.
> 
>     * You can remount with exec permissions with `sudo mount /tmp -o remount,exec`

@tuxedoder, indeed, I had custom mounting options for `/tmp` with `noexec`. After reverting to default mounting, the TCC works.

However, is it really necessary to mount `/tmp` with `exec`? Is it a good practice?

**Comment by tuxedoder** [comment] 2024-05-06 14:23
This wasn't an active decision or change as far as I know. This would require more research to find out if it can be changed and why there is a difference with v2.0.8, but I currently don't have the time to investigate. 

From what I saw online, `noexec` can break things and thus it is a choice between security and usability. I will close this issue since the problem is solved.

**Closed by tuxedoder** 2024-05-06 14:23 UTC
