### ISSUE TITLE
session locked and terminal open (bug)

### ISSUE THREAD

**Issue by D4ftR0ck** [tuxedocomputers/tuxedo-control-center#317] opened 2023-08-30 20:43 UTC
No LSB modules are available.
Distributor ID: Tuxedo
Description:    TUXEDO OS 2
Release:        22.04
Codename:       jammy

---

Hello, I use this version of the OS. I've noticed several problems. When I lock my session and leave my terminal open, I can see that my terminal is accessible from my locked session, without a password...

When I close my screen without locking my session, the computer freezes and I have to reboot...

Are there any fixes planned, or do I have to change OS for better security?

Thank you for your help.

![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/86687768/6da663ff-f819-46a5-939c-1925b9986061)

**Comment by tuxedoder** [comment] 2024-02-28 16:15
This is not an issue because of the tuxedo control center, so I am closing this issue. Nevertheless, I tried to reproduce this problem and I am not able to reproduce it. It may be a bug in the software that is used in Tuxedo OS. We do plan to release plasma 6 which you can try once it is public. Maybe it is fixed in a newer version. If you still have this issue, you can try contacting our support or reinstalling Tuxedo OS. I am only able to help with tcc related topics, but I can open an internal bug ticket if I am able to reproduce it.

**Closed by tuxedoder** 2024-02-28 16:15 UTC
