### ISSUE TITLE
Tuxedo Control Center no temperatures or fan

### ISSUE THREAD

**Issue by mfortini** [tuxedocomputers/tuxedo-control-center#387] opened 2024-05-27 12:59 UTC
Tccd 2.1.8 no errors in the logs

![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/1104926/e9d3a2f2-aecf-4fff-9a6a-1c5ce0f8e93b)

Linux 6.7.12 on Debian Testing

**Comment by tuxedo-wse** [comment] 2024-05-27 21:48
which device?

**Comment by mfortini** [comment] 2024-05-28 08:42
InfinityBook Pro 14 Gen8 (Intel only/without Nvidia RTX 3050)

**Comment by tuxedo-wse** [comment] 2024-05-28 08:56
What is the output of `dkms status`?

**Comment by mfortini** [comment] 2024-05-28 10:00
```
$ sudo dkms status
tuxedo-drivers/4.4.2, 6.6.15-amd64, x86_64: installed
tuxedo-drivers/4.4.2, 6.7.12-amd64, x86_64: installed
```

**Comment by tuxedo-wse** [comment] 2024-05-29 14:55
Have you rebooted since the last update?

**Comment by mfortini** [comment] 2024-05-29 16:15
sure, many times

**Comment by gt-fm-4562** [comment] 2024-05-30 21:12
I have the same issue. 
![image](https://github.com/tuxedocomputers/tuxedo-control-center/assets/100154419/abd8a300-38fe-4bfd-b8be-49510990da85)
Also, I can't find any configurations for battery thresholds anymore.

**Comment by kartoffelsup** [comment] 2024-06-02 17:31
I have a similar issue (Tuxedo Pulse 14) and have this in the tccd logs:
sudo journalctl -u tccd
> Jun 02 19:15:53 host systemd[1]: Started TUXEDO Control Center Service.
Jun 02 19:15:53 host tccd[1162]: Starting daemon v2.1.8 (node: v14.20.0 arch: x64)
Jun 02 19:15:53 host tccd[1162]: No tuxedo-io found on start
...
Jun 02 19:15:54 host tccd[1162]: Daemon started
Jun 02 19:15:55 host tccd[1162]: FanControlWorker: Control unavailable
...
Jun 02 19:15:58 host tccd[1162]: Failed to configure keyboard backlight.

I have `tuxed-drivers` installed (which afaik has `tuxedo-io`?)
> sudo dpkg -s tuxedo-drivers
Package: tuxedo-drivers
Status: install ok installed

**Comment by tuxedo-wse** [comment] 2024-06-03 09:16
I have yet failed to reproduce the issue on a test device, but the not found tuxedo io would explain the missing values in the gui.

What is the output of `lsmod | grep tuxedo`?

If you don't see tuxedo_io pls try running `sudo modprobe tuxedo_io`, `sudo systemctl restart tccd` and restart tcc (right lick on try icon -> exit to fully close it), and for good messure maybe another `lsmod | grep tuxedo`, and `sudo journalctl -u tccd`

**Comment by mfortini** [comment] 2024-06-03 09:27
```
# modprobe -v tuxedo_io
insmod /lib/modules/6.7.12-amd64/updates/dkms/tuxedo_compatibility_check.ko.xz 
modprobe: ERROR: could not insert 'tuxedo_io': Key was rejected by service
```

**Comment by tuxedo-wse** [comment] 2024-06-03 10:06
Did you enable secure boot?

**Comment by tuxedo-wse** [comment] 2024-06-03 10:11
Please give the the output of `mokutil --sb-state` and `mokutil --list-enrolled`

**Comment by mfortini** [comment] 2024-06-03 11:10
Hi, yes secure boot was the cause. It works without secure boot. Suggestion: if tccd can't contact tuxedo-io, maybe it could give an hint

**Comment by tuxedo-wse** [comment] 2024-06-03 13:19
Yeah, the current state of secure boot on TUXEDO OS is turn it off or follow this setup guide: https://github.com/tuxedocomputers/Tuxedo-Linux-Kernel-Self-Signed-Certificate. It is on the medium turn todo list to improve the situation.

**Closed by tuxedo-wse** 2024-06-03 13:19 UTC
