### ISSUE TITLE
cannot create directory ‘./dist/tuxedo-control-center/service-app/native-lib’: File exists

### ISSUE THREAD

**Issue by popey** [tuxedocomputers/tuxedo-control-center#12] opened 2020-04-27 21:34 UTC
Fails to build on Ubuntu 20.04. I tried building master and 1.0.1. Same result.

```
> tuxedo-control-center@1.0.1 copy-native /home/alan/Source/personal/tuxedo-control-center/tuxedo-control-center
> (mkdir ./dist/tuxedo-control-center/service-app/native-lib || true) && cp ./build/Release/TuxedoECAPI.node ./dist/tuxedo-control-center/data/service && cp ./build/Release/TuxedoWMIAPI.node ./dist/tuxedo-control-center/data/service

mkdir: cannot create directory ‘./dist/tuxedo-control-center/service-app/native-lib’: File exists
```

**Comment by vinzv** [comment] 2020-04-28 07:05
Looks like duplicate of #7 
You could try the patch from https://github.com/tuxedocomputers/tuxedo-control-center/issues/7#issuecomment-619113928 as interim solution.

**Comment by tuxedoxt** [comment] 2020-04-28 13:41
Ah yes duplicate.

Inadvertent error output. See: https://github.com/tuxedocomputers/tuxedo-control-center/issues/7#issuecomment-620612082

**Comment by tuxedoxt** [comment] 2020-04-29 12:41
Output suppressed, closing.

**Closed by tuxedoxt** 2020-04-29 12:41 UTC
Labels: bug
